version: "3"

services:
  app-web:
    build:
      context: ./app
      dockerfile: Dockerfile-web
    image: twihaialert-app-web:latest
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
  app-task:
    build:
      context: ./app
      dockerfile: Dockerfile-task
    image: twihaialert-app-task:latest
    env_file:
      - ./.env
    depends_on:
      - db
  proxy:
    image: "caddy:2.1.1-alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"      
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - proxy-data:/data
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - app-web
  db:
    image: mysql:5.7.30
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/twihaialert.cnf:/etc/mysql/conf.d/twihaialert.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${twihaialert_db_name}
      MYSQL_USER: ${twihaialert_db_user}
      MYSQL_PASSWORD: ${twihaialert_db_password}
      TZ: "Asia/Tokyo"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306 -schemas=${twihaialert_db_name} -user=${twihaialert_db_user} -password=${twihaialert_db_password} -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  db-data:
  proxy-data: