version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:4d:4b:8c:c5:61:ad:c5:d3:9e:b5:e5:67:2c:e6:97"
      - run:
          name: prepare ssh
          command: ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
      - run:
          name: git push
          command: |
            git remote add prod $DEPLOY_USER@$DEPLOY_HOST:~/twihaialert/.git
            git push prod main
      - run:
          name: docker build
          command: ssh -tt $DEPLOY_USER@$DEPLOY_HOST "cd ~/twihaialert; sudo docker-compose build"
      - run:
          name: up db
          command: ssh -tt $DEPLOY_USER@$DEPLOY_HOST "cd ~/twihaialert; sudo docker-compose up -d db"
      - run:
          name: migrate
          command: ssh -tt $DEPLOY_USER@$DEPLOY_HOST "cd ~/twihaialert; sudo docker-compose up flyway"
      - run:
          name: up app-web and proxy
          command: |
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "cd ~/twihaialert; sudo docker-compose up -d app-web"
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "cd ~/twihaialert; sudo docker-compose up -d proxy"
      - run:
          name: enable task timer
          command: |
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "sudo cp ~/toot-counter/.circleci/twihaialert-app-task.* /etc/systemd/system/"
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "sudo systemctl daemon-reload"
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "sudo systemctl enable twihaialert-app-task.timer"
            ssh -tt $DEPLOY_USER@$DEPLOY_HOST "sudo systemctl start twihaialert-app-task.timer"
      - slack/status


workflows:
  version: 2
  workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main