version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:4d:4b:8c:c5:61:ad:c5:d3:9e:b5:e5:67:2c:e6:97"
      - run:
          name: prepare ssh
          command: ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
      - run:
          name: git push
          command: |
            git remote add prod $DEPLOY_USER@$DEPLOY_HOST:~/twihaialert/.git
            git push prod main

workflows:
  version: 2
  workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main