version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.14-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache-v1
      - run:
          name: build
          command: |
            cd app
            go build
      - persist_to_workspace:
          root: app
          paths:
            - app
      - save_cache:
          paths:
            - "/go/pkg"
          key: go-cache-v1

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main